version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
